version: '3'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/my_app
      - public_data:/my_app/public
      - tmp_data:/my_app/tmp
      - log_data:/my_app/log
    depends_on:
      - db
  db:
    build:
        context: .
        dockerfile: ./Docker/db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - public_data:/my_app/public
      - tmp_data:/my_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
